# -*- coding: utf-8 -*-
"""pbl project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lEg7sDPB5KtHSafeMdL7CFWbFjJ3j5lX
"""

pip install qrcode

import qrcode

img=qrcode.make('https://open.spotify.com/track/4fsQ0K37TOXa3hEQfjEic1?si=0acb5b9a94894c54')

img.save('SpotifyQRCode.jpg')